### ISSUE TITLE
support for angular 1.3?

### ISSUE THREAD

**Issue by dotob** [oitozero/ngSweetAlert#14]
is there anything preventing to support angular 1.3? it doesnt seems so.

**Comment by awerlang** [comment]
+1

It keeps complaining about it whenever I run `bower update`:

```
├─┬ angular-sweetalert#1.0.4
│ ├── angular#1.3.14 incompatible with ~1.2.0
```

**Comment by oitozero** [comment]
@dotob don't see any reason why it shouldn't work with 1.3. just tested it with 1.3.15 and it works. any specific version you are trying to use?

**Comment by awerlang** [comment]
It just a matter of updating bower.json:

```
"angular":"^1.2.0",
```

That wouldn't require another release to "support" to angular 1.4, 1.5, etc
