### ISSUE TITLE
Call to SweetAlert.swal not working in chrome incognito mode

### ISSUE THREAD

**Issue by mez** [oitozero/ngSweetAlert#19]
I am not sure why, but when I am in a chrome tab which is incognito mode, the alert box doesn't show.
I am not sure what to say about this. It might be me?

**Comment by oitozero** [comment]
Works in normal mode? Any error on the console?
Which Chrome version/OS are you using?

**Comment by mez** [comment]
Yes it does. running chrome Version 40.0.2214.94 (64-bit) on OS X: Yosemite

**Comment by oitozero** [comment]
Also, in 40.0.2214.94 (64-bit) and Yosemite.

Are the examples in demo page working for you in Incognito mode?
http://oitozero.github.io/ngSweetAlert/

![screen shot 2015-02-04 at 09 32 49](https://cloud.githubusercontent.com/assets/4194490/6038077/d021e5f8-ac51-11e4-9814-0fdf9aa3da3c.png)

**Comment by mez** [comment]
Not sure why I didn't think to try that first. Yes, it does work for me. I guess it must be something I am doing. Very strange. Unless you have any clues I am going to close this. Sorry about that!

**Comment by lourdessuello** [comment]
Hi guys i need your help. I am using sweetalert swal and its not working on safari browser

**Comment by puccaso** [comment]
i've noticed something similar. my (result.dismiss === swal.DismissReason.close) works in Chrome but not on Safari :/
