### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by bendikl** [oitozero/ngSweetAlert#20]
The performance is way off compared to the original https://github.com/t4t5/sweetalert in the demos. 

Especially when used on mobile devices or in web apps where dialogs are used alot and require a smooth feeling, it certainly feels slower on rendering / opening dialogue boxes and actions.

Also if you click too quickly on Yes in the multi-step modal @demo(http://oitozero.github.io/ngSweetAlert/#/home) section -> (... and by passing a parameter, you can execute something else for "Cancel".) the dialogue will close without opening the second.

**Comment by JetFault** [comment]
For your last point, it seems to be an upstream change. You can check it out happening here: http://tristanedwards.me/sweetalert

**Comment by oitozero** [comment]
@bendikl could you retry and see if my last commit fixes the issue you had before? http://oitozero.github.io/ngSweetAlert/#/home
thanks
