### ISSUE TITLE
Issue on Cancel in 1.0.4

### ISSUE THREAD

**Issue by afibanez** [oitozero/ngSweetAlert#22]
It can be reproduced in the
[demo](http://oitozero.github.io/ngSweetAlert/#/home) , in the example: *A warning message, with a function attached to the "Confirm"-button*

If you press cancel, the callback is executed anyway.

**Comment by awerlang** [comment]
Workaround (swal function, line 20): 

```js
	if (typeof (arg2) === 'function') {
		var functionAsStr = String(arg2).replace(/\s/g, '');
		var functionHandlesCancel = functionAsStr.substring(0, 9) === "function(" && functionAsStr.substring(9, 10) !== ")";

		var doneFn;
		if (functionHandlesCancel) {
			doneFn = function (isConfirm) {
			    $timeout(function () {
			        arg2(isConfirm);
			    });
			};
		} else {
			doneFn = function () {
			    $timeout(function () {
			        arg2();
			    });
			};
		}
		swal(arg1, doneFn, arg3);
	} else {
		swal( arg1, arg2, arg3 );
	}

```

**Comment by oitozero** [comment]
@afibanez could you retry and see if my last commit fixes the issue you had before? http://oitozero.github.io/ngSweetAlert/#/home
thanks

**Comment by afibanez** [comment]
Hi,
Now the function "A warning message, with a function attached to the "Confirm"-button" does nothing in confirm or cancel button :/

And the function " ... and by passing a parameter, you can execute something else for "Cancel"." works buggy if you press cancel and fast open again and press confirm, the confirm dialog dont show.

Thanks and good job with the wrapper ;)

**Comment by oitozero** [comment]
@afibanez 
For the example "A warning message, with a function attached to the "Confirm"-button", added `closeOnConfirm: false`.

For the example " ... and by passing a parameter, you can execute something else for "Cancel".", tested several times and wasn't able to reproduce it. If you are still having issues, please share some code and will try to take a look asap.
