### ISSUE TITLE
Upgrade to Angular 1.3

### ISSUE THREAD

**Issue by brunomperes** [oitozero/ngSweetAlert#27]
That would be appreciated :)

**Comment by oitozero** [comment]
@brunomperes Could you make a PR for that? Thanks

**Comment by toubou91** [comment]
Hello, 

I just made a <a href="https://github.com/oitozero/ngSweetAlert/pull/28">pull request</a> for this issue, as I firstly, didn't see any progress for two days and secondly, I'm new to bower and I'd like to test if I "got" what I was reading about :) .

Hope this is not a problem for both of you,
Thodoris

**Comment by brunomperes** [comment]
Not at all :)

**Comment by oitozero** [comment]
@toubou91 Thank you for your PR.
cc/ @brunomperes
