### ISSUE TITLE
Question /feature request  : How can I close an alert programmatically (like swal.close() does)

### ISSUE THREAD

**Issue by levequej** [oitozero/ngSweetAlert#29]
Hello,

First, thanks for your tool, it makes integration with angular very easy. 

What would be a proper way to close programmatically an alert created with ngSweetAlert (like swal.close() does)? 

FYI my usecase can't work with the integrated timeout alone  : I am repeating an apiCall with an $interval while  a custom sweetalert with a spinner animated icon is displayed :  I'd like  to dismiss  the sweet alert when I receive the  proper $http.sucess() answer .

thanks for your suggestions.

Julien

**Comment by levequej** [comment]
did not realize that swal.close() was working, my bad.

**Comment by mrudult** [comment]
What if I have multiple instances of `Sweetalert` in my controller?
