### ISSUE TITLE
support for showInputError

### ISSUE THREAD

**Issue by dylanjha** [oitozero/ngSweetAlert#39]
`showInputError` is documented in sweet alert, but appears to not be supported yet for ngSweetAlert

Sweet alert docs:
```js
swal.showInputError
```

error:
```
SweetAlert.showInputError is not a function
```

**Comment by njaw** [comment]
@dylanjha I agree with you. Here is a workaround for you in the meantime. Add this function to the SweetAlert.js file:

```javascript
showInputError: function(message) {
	$rootScope.$evalAsync(function(){
		swal.showInputError( message );
	});
}
```

Then you can easily use as so:

```javascript
SweetAlert.showInputError("You need to write something!");
```
Hope it helps.
