### ISSUE TITLE
Error: Cannot set property 'value' of null

### ISSUE THREAD

**Issue by MacgyverMartins** [oitozero/ngSweetAlert#53]
I install the lib by bower and when I do something like:
```javascript
SweetAlert.swal("Here's a message");
```
I got the error:
`Cannot set property 'value' of null`

My angular version is 1.4.10.
Do you know how I can fix that, or what is happens ?

**Comment by MacgyverMartins** [comment]
Hi!
I fix the bug.
The problem was my code.

**Comment by egorlaw** [comment]
Man, i really need you to tell me what was your problem in the code. I can't get out of this problem. No syntax errors, no typos. SweetAlert.swal("Hello") refuses to work!!!

**Comment by MacgyverMartins** [comment]
The problem was my **bower.json** 
I was working in a legacy code, and my bower.json already had this line:
`"bootstrap-sweetalert": "~0.4.5"`
So, I change it for:
`"ngSweetAlert": "angular-sweetalert#~1.1.0"`

And also prefix Angular and Jquery versions on it:
```
   "resolutions": {
     "jquery": "~2.1.4",
     "angular": "1.4.10"
   }
```

Then, it worked :neckbeard:
