### ISSUE TITLE
publish latest version on NPM

### ISSUE THREAD

**Issue by pvnr0082t** [oitozero/ngSweetAlert#66]
Hi @oitozero ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team and we want to host the library.
I found that the latest version on GitHub is `v1.1.1` but on NPM is `v1.1.0`. Could you please publish the latest versions on npm to make it consistent? Thank you.

https://github.com/cdnjs/cdnjs/issues/9028

**Comment by oitozero** [comment]
1.1.2 is the latest on NPM. thx
