### ISSUE TITLE
Again - Cannot set property 'value' of null

### ISSUE THREAD

**Issue by egorlaw** [oitozero/ngSweetAlert#69]
installed everything as told.
My application works in all, sometimes even the SweetAlert works too.

But in one controller i can't get it to work!

$scope.test = function() {
    SweetAlert.swal("Hello world");
}

template:  <button ng-click="test()">Say hi</button>

gives me an immediate `TypeError: Cannot set property 'value' of null`.

What's the problem? All arguments are injected correctly into my controller, the order is correct- no thing is missing. The rest of the code works perfect.

**Comment by DannyMcwaves** [comment]
hi @egorlaw,
Can you give me a jsFiddle of the code that is causing the problem or detailed rep of the full controller might help.

**Comment by egorlaw** [comment]
hi @DannyMcwaves ,
I've managed to found the problem. 

I loved the animated in css icons that sweetalert uses (like the Success one - with the check on the green circle) and i used it in side my template for the step of the form that is a "thank-you" kinda-like page. During the http async request (before going to that step) i pop out $uibModal.open and make a loading. After resolving the modal with $scope.$close i try to make the user awar of the successful transaction with an SweetAlert.swal, but the error would make the thing impossible.

What i've found is that NEVER USE any of the markup / classes that are sweet-alert native. Because it'll try to instantiate them as already existing on page and try to clean the mess. But there's no sweetalert on page so far - so it lauches the error.

My template had this element:
`
<div class="sweet-alert animate">
    <div class="sa-icon sa-success animate" style="display: block;">
        <span class="sa-line sa-tip animateSuccessTip"></span>
        <span class="sa-line sa-long animateSuccessLong"></span>
        <div class="sa-placeholder"></div>
        <div class="sa-fix"></div>
    </div>
</div>
`
This breaks the sweetalert behaviour. Probably any other part of the swal constructs as overlays and body or else - will break the stuff too.

Don't try this at home folks ;)

**Comment by DannyMcwaves** [comment]
Hi @egorlaw 
Great. I am very glad that you have fixed that.
I saw your profile and I realized you can code python. I was wondering if you have enough time,
so we can collaborate on this python project I am trying to work on.
If you have enough time, just let me know.

**Comment by egorlaw** [comment]
Sorry man, but im full with angularjs and drupal projects atm. Free Time is
familiare though

**Comment by DannyMcwaves** [comment]
cool. Are you using angular 2, @egorlaw ??

**Comment by egorlaw** [comment]
Still learning. Ti has quite steep learning curve imho

**Comment by DannyMcwaves** [comment]
Nice. If you have any projects on angular or angular 2 that you think you might need collaboration on, just let me know. If you have an understanding with angular 1, can you check this project I created and see if you can find any issues. Also  I am following you, can you follow back?

**Comment by DannyMcwaves** [comment]
Nice. If you have any projects on angular or angular 2 that you think you might need collaboration on, just let me know. If you have an understanding with angular 1, can you check this project I created, ngSocial in in my repo, and see if you can find any issues. Also  I am following you, can you follow back?
