### ISSUE TITLE
TypeError: swal is not a function

### ISSUE THREAD

**Issue by Sunilgn** [oitozero/ngSweetAlert#80]
hi all,

I am using sweet alert since 2 months, 
suddenly I got an error saying swal is not a function
can u please provide me a workaround for this

"angular-sweetalert": "latest" ------> this is the bower.json entry

Thanks

**Comment by marolt** [comment]
Hi @Sunilgn 

check issue #78.

**Comment by Sunilgn** [comment]
@marolt  thanks for the reply
but I have followed the issue #78, but still getting the same error
I have manually installed the sweetalert 1.1.3 and tried with 
"angular-sweetalert": "https://github.com/theviralab/ngSweetAlert.git#c0b746e"
angular-sweetalert#c0b746e bower_components\angular-sweetalert
├── angular#1.6.6
└── sweetalert#1.1.3

as well, but no luck, can u please help me out

**Comment by rajalive28** [comment]
@Sunilgn try this by adding to your bower.json:

"ngSweetAlert": "https://github.com/theviralab/ngSweetAlert.git#c0b746e"

Let me know if it worked!!

**Comment by Sunilgn** [comment]
@rajalive28 thanks for the reply
I tried it, but No luck  :(
can u please let me know, is there any information I need to provide

**Comment by Sunilgn** [comment]
@rajalive28   @marolt, my bad 
sweet alert works fine with the given workaround, there was some configuration issue in my setup
Thank you :)
