### ISSUE TITLE
Reason for using $timeout?

### ISSUE THREAD

**Issue by Ilyes512** [oitozero/ngSweetAlert#9]
Hi,

Is there a specific reason why you used `$timeout`? The difference with the vanila SweetAlert is quite noticeable and feels less performed because of it.

**Comment by ajwhite** [comment]
The only difference between `$timeout` and `setTimeout` is that `$timeout` invokes `$rootScope.$apply` and triggers `setTimeout` via `$browser.defer`.

`$rootScope.$apply` would do just fine here

**Comment by oitozero** [comment]
fixed with https://github.com/oitozero/ngSweetAlert/commit/922d179a59facb6fadf1ab8354c4f55fcf3e8411.

thanks for the input, everyone.
